var buf = new Buffer(550);

var len = buf.write("Praveen hegdesjhdfhoidfhoidfhdfoijfdoijhfkhfkjjhfdkdhghuthgkjhgkjhgfkjhgkghkghkjgjhkgjhkgjhgkjhgkjhgfhgfkgfhkgjhgkjhgfkhgfkjhgfkhgkjghkjghkjrehiuiurehurehireuruireiuhrvjkhdfkfhkfdjfkjhfdkhfdkfjhfdfhsdjkhkdjaslkasakdbncmnbcnbcbxncbxbmxcbbcxmclxlalksjj;jiodsjldkskjkerhiutrhiutuhrtihntkjfnkfjndfeihfdkjfhkjfhkfjdhfdkfkjdfjkfjfdhfdkkhfdkjfoihfdoihfdoioifhdiufudfdiuhfdiuhfdiuiufdufdhufdhiudfhiufdhfidhfdhfdkkhfdfhdkjfdkjfdhfkdjhfdkjhfdkjfkjfdkjfjdkjfdjfdkjfdkjriugewihweoihewoewhiwehirehyurheutbfdjbfdjbfd");

console.log ("Octects written  " + len);